package: tinymce4
version: '1.2.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/tinymce4

requires:
    redaxo: ^5.1.0
page:
    title: 'Tinymce4'  
    perm: tinymce4[]
